SDHCI card support changed to MMC and extended to support both Ricoh and Realtek linux config, board config and x230 configs and mount-sdcard script modified accordingly

diff --git a/initrd/bin/mount-sdcard b/initrd/bin/mount-sdcard
--- a/initrd/bin/mount-sdcard
+++ b/initrd/bin/mount-sdcard
@@ -21,31 +21,45 @@ enable_sdcard()
     #alias insmod='busybox insmod'
     #debug "Testing insmod in enable_sdcard just after alias: $(insmod)"
     #even last debug happens after PCR5 being modified.... Changing tactic. Duplicating logic.
-    if [ "$CONFIG_LINUX_SDHCI" = "y" ]; then
-      if ! lsmod | grep -q mmc_core; then
-        busybox insmod /lib/modules/mmc_core.ko \
-        || die "mmc_core: module load failed"
-      fi
-      if ! lsmod | grep -q mmc_block; then
-        busybox insmod /lib/modules/mmc_block.ko \
-        || die "mmc_block: module load failed"
-      fi
-      if ! lsmod | grep -q cqhci; then
-        busybox insmod /lib/modules/cqhci.ko \
-        || die "cqhci: module load failed"
-      fi
-      if ! lsmod | grep -q sdhci; then
-        busybox insmod /lib/modules/sdhci.ko \
-        || die "sdhci: module load failed"
-      fi
-      if ! lsmod | grep -q sdhci_pci; then
-        busybox insmod /lib/modules/sdhci-pci.ko \
-        || die "sdhci-pci: module load failed"
-      fi
+    #
+    #Ricoh
+    if ! lsmod | grep -q mmc_core; then
+      busybox insmod /lib/modules/mmc_core.ko \
+      || die "mmc_core: module load failed"
+    fi
+    if ! lsmod | grep -q mmc_block; then
+      busybox insmod /lib/modules/mmc_block.ko \
+      || die "mmc_block: module load failed"
+    fi
+    if ! lsmod | grep -q cqhci; then
+      busybox insmod /lib/modules/cqhci.ko \
+      || die "cqhci: module load failed"
+    fi
+    if ! lsmod | grep -q sdhci; then
+      busybox insmod /lib/modules/sdhci.ko \
+      || die "sdhci: module load failed"
+    fi
+    if ! lsmod | grep -q sdhci_pci; then
+      busybox insmod /lib/modules/sdhci-pci.ko \
+      || die "sdhci-pci: module load failed"
+    fi
+    #Realtek
+    if ! lsmod | grep -q mfd-core; then
+      busybox insmod /lib/modules/mfd-core.ko \
+      || die "mfd-core: module load failed"
+    fi
+    if ! lsmod | grep -q rtsx_pci; then
+      busybox insmod /lib/modules/rtsx_pci.ko \
+      || die "rtsx_pci: module load failed"
+    fi
+    if ! lsmod | grep -q rtsx_pci_sdmmc; then
+      busybox insmod /lib/modules/rtsx_pci_sdmmc.ko \
+      || die "rtsx_pci_sdmmc: module load failed"
     fi
   else
-    #TODO: For some reason, the alias is not kept outside of the if so we replicate here with insmod which measures modules
-    if [ "$CONFIG_LINUX_SDHCI" = "y" ]; then
+    #TODO: For some reason, the alias is not kept outside of the if so we replicate here with busybox insmod which measures modules
+    if [ "$CONFIG_LINUX_MMC" = "y" ]; then
+      #Common
       if ! lsmod | grep -q mmc_core; then
         insmod /lib/modules/mmc_core.ko \
         || die "mmc_core: module load failed"
@@ -54,6 +68,7 @@ enable_sdcard()
         insmod /lib/modules/mmc_block.ko \
         || die "mmc_block: module load failed"
       fi
+      #Ricoh specifics
       if ! lsmod | grep -q cqhci; then
         insmod /lib/modules/cqhci.ko \
         || die "cqhci: module load failed"
@@ -65,6 +80,19 @@ enable_sdcard()
       if ! lsmod | grep -q sdhci_pci; then
         insmod /lib/modules/sdhci-pci.ko \
         || die "sdhci-pci: module load failed"
+      fi
+      #Realtek specifics
+      if ! lsmod | grep -q mfd-core; then
+        insmod /lib/modules/mfd-core.ko \
+        || die "mfd-core: module load failed"
+      fi
+      if ! lsmod | grep -q rtsx_pci; then
+        insmod /lib/modules/rtsx_pci.ko \
+        || die "rtsx_pci: module load failed"
+      fi
+      if ! lsmod | grep -q rtsx_pci_sdmmc; then
+        insmod /lib/modules/rtsx_pci_sdmmc.ko \
+        || die "rtsx_pci_sdmmc: module load failed"
       fi
     fi
   fi
